### ISSUE TITLE
compress large files on FTP server?

### ISSUE THREAD

**Issue by ctb** [cai91/GPD#3]
hello, thank you for making all of this so easy to find and use!

Some of the files here,

http://ftp.ebi.ac.uk/pub/databases/metagenomics/genome_sets/gut_phage_database/

are extremely large and are uncompressed. I wanted to suggest that some compressed version of them would be useful, too. But no big deal if not - the data is available and that's the important part!

**Comment by alexmsalmeida** [comment]
Hi Titus!

Thanks for flagging that. You are right, I just compressed a couple of the big files in there (the faas and the orthology assignment ones). Hope this makes the download process a bit easier.

Best,
Alex

**Comment by ctb** [comment]
hah! it's now small enough that I'm going to kill my ongoing transfer and restart! 😆 thank you!
